# Generated by Django 5.1.5 on 2025-03-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='sathya@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
