# Generated by Django 5.1.5 on 2025-03-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_webpage_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='age',
            field=models.IntegerField(default=22),
        ),
    ]
